import Head from 'next/head'
import styles from './index.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Home</h1>
      </main>

      <footer>
        <p>Footer</p>
      </footer>
    </div>
  )
}
